name: app
type: php:8.2

runtime:
    extensions:
        - dom
        - libxml
        - curl

web:
    locations:
        "/":
            allow: true
            passthru: "/index.php"
            index:
                - index.php
            scripts: true
            expires: -1
            rules:
                \.php$:
                    allow: true

disk: 512
