name: zerobot
type: php:8.2

runtime:
  extensions:
    - dom
    - xml
    - curl
    - mbstring
    - fileinfo
    - pdo
    - iconv

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      allow: true
      expires: -1

disk: 1024

mounts:
  "/public/views.php":
    source: local
    source_path: "views.php"

hooks:
  deploy: |
    set -e
    mkdir -p /tmp/sessions
    chmod -R 777 /tmp/sessions
    chmod 666 public/views.php 2>/dev/null || true
    chmod 755 public
