name: app
type: php:8.2

runtime:
  extensions:
    - dom
    - xml
    - curl
    - mbstring
    - fileinfo
    - pdo

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      allow: true
      expires: -1  # Disable caching for PHP files

disk: 1024

mounts:
  "/public/views": "shared:files/views"

hooks:
  build: |
    set -e
    php -m  # Verify installed extensions
  deploy: |
    set -e
    mkdir -p public/views
    chmod -R 777 public/views
