name: zerobot
type: php:8.2

runtime:
  extensions:
    - dom
    - libxml
    - curl
    - session
    - mbstring
    - fileinfo

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      allow: true
      scripts: false
      expires: -1

disk: 1024

mounts:
  "/public/views": "shared:files/views"

hooks:
  build: |
    set -e
    # Install any required PHP extensions
    php -m
  deploy: |
    set -e
    # Ensure views directory exists and is writable
    mkdir -p public/views
    chmod -R 777 public/views
