name: app
type: php:8.2

runtime:
    extensions:
        - dom
        - curl
        - simplexml
        - xml

web:
    locations:
        "/":
            allow: true
            passthru: "/index.php"
            index: [index.php]
            scripts: true
            expires: -1

disk: 512
mounts:
    '/tmp':
        source: local
        source_path: tmp
