name: app
type: php:8.2

runtime:
  extensions:
    - dom
    - xml
    - curl
    - mbstring
    - fileinfo
    - session
    - pdo
    - openssl

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      allow: true

disk: 1024

mounts:
  "/public/views": "shared:files/views"

hooks:
  build: |
    set -e
    php -m
  deploy: |
    set -e
    mkdir -p public/views
    chmod -R 777 public/views
    chmod -R 755 public
